### ISSUE TITLE
Phase 4 schematic looks to be incomplete

### ISSUE THREAD

**Issue by wa6pzb** [jonscheiding/phone-ringer#1]
Reviewing your work I noticed the H-Bridge is not fully connected to the step-up transformer through the RC network.

Thanks for posting this, I am actual building something similar using two relays as the H-bridge.

**Comment by jonscheiding** [comment]
Thanks for the comment! It's been so long since I looked at this, the context is totally gone 🤣 can you point me to where the missing connection is?

**Comment by jonscheiding** [comment]
Nevermind, I was able to remember and fix it. Thanks again!
